- hosts: webservers
  become: yes
  gather_facts: no
  vars: 
    users: 
      - jaime
      - sansa
      - robert
  tasks:
    - name: create users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"

    - name: git install
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
    - name: Create git config file
      ansible.builtin.template:
        src: gitconfig.j2
        dest: "/home/{{ item }}/.gitconfig"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ users }}"

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0700'
      loop: "{{ users }}"
    
    - name: Upload public key to authorized_keys
      ansible.builtin.copy:
        src: /home/akim/.ssh/id_rsa.pub
        dest: "/home/{{ item }}/.ssh/authorized_keys"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0600'
      loop: "{{ users }}"
